version: "3.7"

services:
  db:
    image: mysql:8.0.1
    container_name: my-own-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "5432:5432"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-own-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    links:
      - "db:my-own-mysql"
